name = "fantetic-nav-cf"
main = "cloudflare/worker/src/index.ts"
compatibility_date = "2026-04-07"

[assets]
directory = "./ui/build"
binding = "ASSETS"
not_found_handling = "single-page-application"
html_handling = "drop-trailing-slash"

[[d1_databases]]
binding = "DB"
database_name = "fantetic-nav"
database_id = "018038b8-5094-40c6-8816-495b7693baf4"
migrations_dir = "cloudflare/migrations"

[[r2_buckets]]
binding = "LOGO_BUCKET"
bucket_name = "fantetic-nav-logos"
preview_bucket_name = "fantetic-nav-logos-preview"
